# Generated by Django 2.2.11 on 2020-03-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200327_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionId', models.IntegerField()),
                ('description', models.TextField()),
                ('document', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Document')),
                ('policyitems', models.ManyToManyField(null=True, to='backend.PolicyItem')),
            ],
            options={
                'unique_together': {('document', 'descriptionId')},
            },
        ),
    ]
