# Generated by Django 2.2.11 on 2020-03-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_documentstructure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentstructure',
            unique_together=set(),
        ),
    ]
