# Generated by Django 2.2.11 on 2020-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200328_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronlog',
            name='userNumber',
            field=models.IntegerField(default=0),
        ),
    ]
