# Generated by Django 2.2.11 on 2020-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cronlog_usernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyitem',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Document'),
        ),
    ]
