# Generated by Django 2.2.11 on 2020-04-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_policyitem_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyitem',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Document'),
        ),
    ]
