# Generated by Django 2.2.11 on 2020-04-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200408_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyitem',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Document'),
        ),
    ]
