# Generated by Django 2.2.11 on 2020-04-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_policyitem_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyitem',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Document'),
        ),
    ]
