# Generated by Django 2.2.11 on 2020-04-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200408_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='gavatar',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='policyitem',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Document'),
        ),
    ]
