# Generated by Django 2.2.11 on 2020-04-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200410_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='policyId',
        ),
        migrations.AddField(
            model_name='question',
            name='policy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PolicyItem'),
        ),
    ]
