# Generated by Django 2.2.11 on 2020-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_overduehandbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhandbook',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
